### ISSUE TITLE
set up basic data types

### ISSUE THREAD

**Issue by gabrielrussoc** [maratonime/simone#11]
for now, the contest data type is enough

```
contest:
  - name: string
  - code: string
  - judge: enum
  - starttime?: date
  - duration: integer
  - status?: enum
  - url: string
  - description?: string
```
